version: '3'
services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"

  console:
    build: "./trinitycore"
    depends_on:
      - database
    volumes:
      - "./config:/app/etc"
      - "./data:/data"
